## КМ-3

На квадрате n*n на верхней стороне сгенерировать случайное распределение частиц (от 1 до n-1). Построить анимацию распространения частиц вниз. Частица в следующем слое появляется, если в предыдущем слое с ней смежны от k1 до k2 частиц. В пользовательский интерфейс выносятся: число случайно расположенных частиц в верхнем слое от 1 до n-1, а также n, m, k1, k2, интервал между кадрами. Анимируйте распространение частиц от верхнего к нижнему слою. Вывод можно сделать с помощью функции matplotlib imshow().

In [77]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
from ipywidgets import widgets
from time import sleep


def gen_rand_lvl(n, count):
    res = np.zeros(n)
    i = np.array(range(count))
    res[i] = 1
    np.random.shuffle(res)
    return res

def get_next_lvl(pr_lvl, k1, k2):
    new_lvl = np.zeros(len(pr_lvl))
    pr_lvl = np.insert(np.zeros(2), 1, pr_lvl)
    for i in range(1, len(pr_lvl)-1):
        if k1 <= (pr_lvl[i-1], pr_lvl[i], pr_lvl[i+1]).count(1) <= k2:
            new_lvl[i-1] = 1
    return new_lvl

#tests
k1, k2 = 1, 2
n, count = 12, 6
pr_lvl = gen_rand_lvl(n, count)
next_lvl1 = get_next_lvl(pr_lvl, k1, k2)
next_lvl2 = get_next_lvl(next_lvl1, k1, k2)
pr_lvl, next_lvl1, next_lvl2 

(array([0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1.]),
 array([1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.]),
 array([1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1.]))

In [78]:
def main(*args):
    n = w_n.value
    count = w_count.value
    k1, k2 = w_k1.value, w_k2.value
    delay = w_delay.value
    matrix = np.zeros((n, n))
    matrix[0] = gen_rand_lvl(n, count)
    with out2:
        for i in range(1, len(matrix)):
            clear_output(wait=True)
            matrix[i] = get_next_lvl(matrix[i-1], k1, k2)
            plt.imshow(matrix, cmap='gray')# Частицы белые
            plt.show()
            sleep(delay)

            
out1 = widgets.Output(layout={'width': '50%'})
out2 = widgets.Output(layout={'width': '50%'})
title = widgets.HTML('<h4>Анимация распростронения частиц вниз</h4>')
w_n_L = widgets.Label('Сторона квадрата')
w_n = widgets.IntSlider(description='', min=0, max=100, step=1, value=60)
w_count_L = widgets.Label('Число случайно расположенных частиц')
w_count = widgets.IntSlider(description='', min=0, max=100, step=1, value=40)
w_k1_L = widgets.Label('k1')
w_k1 = widgets.FloatSlider(description='', min=0, max=3, step=1, value=1)
w_k2_L = widgets.Label('k2')
w_k2 = widgets.FloatSlider(description='', min=0, max=3, step=1, value=2)
w_delay_L = widgets.Label('Интервал между кадрами')
w_delay = widgets.FloatSlider(description='', min=0, max=1, step=0.01, value=0.2)
button = widgets.Button(description='Запустить', button_style='primary')
button.on_click(main)
display(widgets.HBox([out1, out2]))
with out1:
    display(title,
            w_n_L, w_n,
            w_count_L, w_count,
            w_k1_L, w_k1,
            w_k2_L, w_k2,
            w_delay_L, w_delay,
            button)